version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/never-stray
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      runas: ubuntu
      timeout: 300
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: ubuntu
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      runas: ubuntu
      timeout: 720
  ApplicationStart:
    - location: scripts/start-server.sh
      runas: ubuntu
      timeout: 300
  
      