version: '3.4'
services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: base
    command: yarn start
    volumes:
      - ./backend:/app   
    environment:
      - APP_PORT=8080
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.production
    networks:
      - app_net

  frontend: 
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    networks:
      - app_net
  
networks:
  app_net: