version: '3.4'
services:
  backend:
    container_name: backend
    restart: always
    image: backend:latest
    command:
      - /bin/sh
      - -c
      - |
        sh /backend/src/scripts/entrypoint.sh
        yarn start
    volumes:
      - ./backend:/app
    environment:
      - APP_PORT=8080
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.development
    networks:
      - app_net

  cron:
    container_name: cron
    image: cron:latest
    restart: always
    command: yarn crawler
    environment:
      - JOB_PORT=8081
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env.development
    depends_on:
      - db
    networks:
      - app_net

  frontend:
    container_name: frontend
    restart: always
    image: frontend:latest
    ports:
      - "3600:3600"
    env_file:
      - ./frontend/.env.development
    networks:
      - app_net

networks:
  app_net:
