version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "80:8080" # Bind port 80 of host to 3000 of container
    container_name: frontend-docker
    depends_on:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./backend
    environment:
      - APP_PORT=5555
    ports:
      - "5555:5555"
    container_name: backend-docker