version: '3.4'
services:
  backend:
    container_name: backend
    image: node:16.13.2-slim 
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    command:
      - /bin/sh
      - -c
      - |
        /backend/src/scripts/wait-for-it.sh 127.0.0.1:3306 -- echo "DB is up"
        sh /backend/src/scripts/entrypoint.sh
        yarn start
    volumes:
      - ./backend:/app
    environment:
      - APP_PORT=8080
      - TYPEORM_HOST=db
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.development
    depends_on:
      - db
    networks:
      - app_net

  cron:
    container_name: cron
    image: node:16.13.2-slim 
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        echo "Wait for DB service to start"
        sleep 10
        yarn crawler
    environment:
      - JOB_PORT=8081
      - TYPEORM_HOST=db
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env.development
    depends_on:
      - db
    networks:
      - app_net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3600:3600"
    env_file:
      - ./frontend/.env.development
    networks:
      - app_net

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    command: --authentication_policy=mysql_native_password
    env_file:
      - ./backend/.env.development
    environment:
      TZ: Asia/Taipei
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    networks:
      - app_net

volumes:
  mysql-data:

networks:
  app_net:
