version: '3.4'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    command:
      - /bin/sh
      - -c
      - |
        /backend/src/scripts/wait-for-it.sh 127.0.0.1:3306 -- echo "DB is up"
        sh /backend/src/scripts/entrypoint.sh
        yarn start
    volumes:
      - ./backend:/app
    environment:
      - APP_PORT=8080
      - TYPEORM_HOST=db
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.production
    depends_on:
      - db
    networks:
      - app_net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env.production
    networks:
      - app_net

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    command: --authentication_policy=mysql_native_password
    env_file:
      - ./backend/.env.production
    environment:
      TZ: Asia/Taipei
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    networks:
      - app_net

volumes:
  mysql-data:

networks:
  app_net:
