version: '3.4'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
      - ./nginx/cert:/etc/nginx/cert
    networks:
      - app_net

  backend:
    container_name: backend
    restart: always
    image: backend:latest
    command:
      - /bin/sh
      - -c
      - |
        sh /backend/src/scripts/entrypoint.sh
        yarn start
    volumes:
      - ./backend:/app
    environment:
      - APP_PORT=8080
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.production
    networks:
      - app_net

  cron:
    container_name: cron
    image: cron:latest
    restart: always
    command: yarn crawler
    environment:
      - JOB_PORT=8081
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env.production
    networks:
      - app_net

  frontend:
    container_name: frontend
    restart: always
    image: frontend:latest
    ports:
      - "3600:3600"
    env_file:
      - ./frontend/.env.production
    networks:
      - app_net
    deploy:
      resources:
        limits:
          memory: 400M

networks:
  app_net:
